parse_config:
  zmk_preamble: "#include <zmk-helpers/key-labels/36.h>"
  zmk_additional_includes:
    - "modules/helpers/include"

draw_config:
  footer_text: "rael-dev/zmk-config-corne"
  dark_mode: auto