draw_config:
  key_w: 65
  key_h: 65
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 8.0
  inner_pad_h: 8.0
  combo_w: 20
  combo_h: 18
  dark_mode: off
  append_colon_to_layer_header: false

  svg_extra_style: |
    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      font-kerning: normal;
      text-rendering: optimizeLegibility;
    }
 
    text.label {
      stroke: #dfdfde;
      stroke-width: 28;
      stroke-linejoin: round;
    }

    text.hold {
       font-size: 11px;
       opacity: 0.9;
       translate: 0px -4px;
       text-anchor: middle;
       dominant-baseline: auto;
    }

    rect.combo, rect.combo-separate {
      opacity: 0.9;
      stroke: #000000;
      stroke-width: 0.5;
      fill: #FFA24A;
    }

    path.combo {
      stroke-dasharray: 4, 4;
      stroke-opacity: 1.0;
      stroke: #FFA24A;
    }

    rect.key.held {
      fill: #FF545D;
    }

    .trans.tap, .ghost.tap {
      opacity: 0.5;
    }

    .shifted {
      translate: -14px 1px;
      opacity: 1.0;
      stroke: #5C96FF;
    }

    .toggle.shifted {
      translate: -12px 17px;
      opacity: 1.0;
    }
    .toggle.hold {
      translate: 12px -25px;
    }

    .text_with_symbol.tap {
      translate: -1px 1px;
    }
    .text_with_symbol.shifted {
      translate: 8px 13px;
      font-size: 10px;
      opacity: 1.0;
    } 

    .combo.text_with_symbol.tap {
      translate: -1px 1px;
    }
    .combo.text_with_symbol.shifted {
      translate: 7px 5px;
      font-size: 8px;
      opacity: 1.0;
    }
  
  glyph_tap_size: 18
  glyph_hold_size: 13
  glyph_shifted_size: 14
  
parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:circle-small$$
  toggle_label: $$mdi:toggle-switch$$
  trans_legend:
    tap: $$mdi:chevron-down$$
    type: trans
  zmk_preamble: "#include <zmk-helpers/key-labels/36.h>"
  zmk_additional_includes:
    - "modules/helpers/include"

  raw_binding_map: 
    '&sys_reset': $$mdi:backup-restore$$
    '&bootloader': $$mdi:progress-download$$
    '&studio_unlock': $$mdi:lock-open-outline$$
    '&hml LA(LCTRL) TAB': $$mdi:keyboard-tab$$
    '&hml_repeat LS(LCTRL) 0': $$mdi:repeat$$
    '&key_repeat': $$mdi:repeat$$
    '&caps_word': $$mdi:caps-lock$$
    '&mt LA(F4) LC(W)': $$mdi:close-box-outline$$
    '&alt_tabber': $$mdi:swap-horizontal$$
    '&kns_lock': $$mdi:apple-keyboard-caps$$
    '&dgrv_macro': '``'
    '&brc_macro': '[]'
    '&par_macro': '()'
    '&bkt_macro': '{}'
    '&lgt_macro': '<>'
    
    '&kp LC(BSPC)': $$mdi:backspace$$
    '&kp LC(DEL)': $$mdi:backspace-reverse$$
    '&kp LS(TAB)': $$mdi:keyboard-tab-reverse$$
    
    '&kp LC(TAB)': $$mdi:arrow-right-bold-box$$
    '&kp LC(LS(TAB))': $$mdi:arrow-left-bold-box$$

    '&kp LC(LG(LEFT))': $$mdi:arrow-left-bold-box-outline$$
    '&kp LC(LG(RIGHT))': $$mdi:arrow-right-bold-box-outline$$
    
    '&kp LC(LS(LALT))': $$mdi:star-three-points-outline$$
    '&kp LC(LS(LA(LGUI)))': $$mdi:star-four-points-outline$$
    '&kp LC(HOME)': $$mdi:format-vertical-align-top$$
    '&kp LC(END)': $$mdi:format-vertical-align-bottom$$

    '&kp LC(INS)': $$mdi:content-copy$$
    '&kp LC(C)': $$mdi:content-copy$$
    '&kp LS(INS)': $$mdi:content-paste$$
    '&kp LC(V)': $$mdi:content-paste$$
    '&kp LS(DEL)': $$mdi:content-cut$$
    '&kp LC(X)': $$mdi:content-cut$$
    '&kp LC(Z)': $$mdi:undo$$
    '&kp LC(Y)': $$mdi:redo$$
    '&kp LC(LS(Z))': $$mdi:redo$$

    '&kp LC(F)': $$mdi:text-search$$
    '&kp LC(W)': $$mdi:close-box-outline$$
    '&kp LA(F4)': $$mdi:close-box-outline$$

    '&kp LC(PLUS)': $$mdi:magnify-plus-outline$$
    '&kp LC(MINUS)': $$mdi:magnify-minus-outline$$
    '&kp LC(N0)': $$mdi:magnify-remove-outline$$

    '&kp LG(L)': $$mdi:lock-outline$$
    '&hmr LCTRL LG(LC(LEFT))': 'DSK_PREV'
    '&hmr LALT LG(LC(RIGHT))': 'DSK_NEXT'
    '&kp LG(LC(LS(Q)))': 'PIN_WIN'
    '&kp LG(LC(LS(A)))': 'PIN_APP'
    '&kp LA(GRAVE)': 'DSK_MNGR'

    '&win_sleep': $$mdi:sleep$$
    '&rename': $$mdi:rename-outline$$
    '&comment': $$mdi:comment-edit-outline$$
    '&uncomment': $$mdi:comment-remove$$
    '&cpp_header_hop': $$mdi:file-arrow-left-right$$
    '&search_members': $$mdi:database-search$$
    '&context_actions': $$mdi:format-list-group-plus$$
    
    '&td_sqt_dqt':
      tap: "'"
      shifted: '"'

    '&kp COMMA':
      tap: ','
      shifted: ';'
    
    '&kp DOT':
      tap: '.'
      shifted: ':'

    '&ht_qu Q 0':
      tap: 'QU'
      hold: 'Q'
    
    '&out OUT_BLE': $$mdi:bluetooth$$
    '&out OUT_USB': $$mdi:usb$$
    '&out OUT_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
      shifted: $$mdi:usb$$
      type: toggle
    
    '&bt BT_CLR':
      tap: $$mdi:bluetooth$$
      shifted: $$mdi:close-thick$$
      type: text_with_symbol
    '&bts 0':
      tap: $$mdi:bluetooth-connect$$
      shifted: '0'
      type: text_with_symbol
    '&bts 1':
      tap: $$mdi:bluetooth-connect$$
      shifted: '1'
      type: text_with_symbol
    '&bts 2':
      tap: $$mdi:bluetooth-connect$$
      shifted: '2'
      type: text_with_symbol
    '&bts 3':
      tap: $$mdi:bluetooth-connect$$
      shifted: '3'
      type: text_with_symbol
    '&bts 4':
      tap: $$mdi:bluetooth-connect$$
      shifted: '4'
      type: text_with_symbol
    '&bts_0':
      tap: $$mdi:bluetooth-connect$$
      shifted: '0'
      type: text_with_symbol
    '&bts_1':
      tap: $$mdi:bluetooth-connect$$
      shifted: '1'
      type: text_with_symbol
    '&bts_2':
      tap: $$mdi:bluetooth-connect$$
      shifted: '2'
      type: text_with_symbol
    '&bts_3':
      tap: $$mdi:bluetooth-connect$$
      shifted: '3'
      type: text_with_symbol
    '&bts_4':
      tap: $$mdi:bluetooth-connect$$
      shifted: '4'
      type: text_with_symbol
    '&bt BT_DISC 0':
      tap: $$mdi:bluetooth-off$$
      shifted: '0'
      type: text_with_symbol
    '&bt BT_DISC 1':
      tap: $$mdi:bluetooth-off$$
      shifted: '1'
      type: text_with_symbol
    '&bt BT_DISC 2':
      tap: $$mdi:bluetooth-off$$
      shifted: '2'
      type: text_with_symbol
    '&bt BT_DISC 3':
      tap: $$mdi:bluetooth-off$$
      shifted: '3'
      type: text_with_symbol
    '&bt BT_DISC 4':
      tap: $$mdi:bluetooth-off$$
      shifted: '4'
      type: text_with_symbol

    '&smart_mouse': $$mdi:mouse$$
    '&mmv MOVE_UP':
      tap: $$mdi:mouse$$
      shifted: UP
      type: text_with_symbol
    '&mmv MOVE_DOWN':
      tap: $$mdi:mouse$$
      shifted: DOWN
      type: text_with_symbol
    '&mmv MOVE_LEFT':
      tap: $$mdi:mouse$$
      shifted: LEFT
      type: text_with_symbol
    '&mmv MOVE_RIGHT':
      tap: $$mdi:mouse$$
      shifted: RIGHT
      type: text_with_symbol

    '&msc SCRL_UP': 'SCROLL_U'
    '&msc SCRL_DOWN': 'SCROLL_D'
    '&msc SCRL_LEFT': 'SCROLL_L'
    '&msc SCRL_RIGHT': 'SCROLL_R'
    
    '&mkp LCLK': $$mdi:cursor-default-click-outline$$
    '&mkp RCLK': $$mdi:cursor-default-click$$
    '&mkp MB3':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 3
      type: text_with_symbol
    '&mkp MB4':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 4
      type: text_with_symbol
    '&mkp MCLK':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: MID
      type: text_with_symbol
    '&mkp MB5':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 5
      type: text_with_symbol

    '&tb_mo_scroll':
      tap: $$mdi:billiards$$
      shifted: $$mdi:arrow-up-down$$
      type: text_with_symbol

    '&tb_tg_scroll':
      tap: $$mdi:billiards$$
      shifted: $$mdi:arrow-up-down$$
      hold: $$mdi:toggle-switch$$
      type: text_with_symbol

    '&tbs_mt 0 0':
      tap: $$mdi:billiards$$
      shifted: $$mdi:arrow-up-down$$
      hold: $$mdi:toggle-switch$$
      type: text_with_symbol

    '&tb_bootloader':
      tap: $$mdi:billiards$$
      shifted: $$mdi:progress-download$$
      type: text_with_symbol

    '&tb_cyc_dpi':
      tap: $$mdi:billiards$$
      shifted: $$mdi:speedometer$$
      type: text_with_symbol

    '&ind_con':
      tap: $$mdi:bluetooth$$
      shifted: $$mdi:help-circle-outline$$
      type: text_with_symbol

    '&ind_bat': $$mdi:battery-heart-outline$$

  zmk_combos:
    combo_mouse:
      align: top
    combo_cut:
      align: bottom
    combo_rpar:
      draw_separate: true
    combo_lpar:
      draw_separate: true
      
  zmk_keycode_map:
    LALT: ALT
    
    SPACE: $$mdi:keyboard-space$$
    ESC: $$mdi:keyboard-esc$$

    RETURN: $$mdi:keyboard-return$$
    RET: $$mdi:keyboard-return$$
    
    BACKSPACE: $$mdi:backspace-outline$$
    BSPC: $$mdi:backspace-outline$$
    
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
    
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    
    LSHFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    
    RSHFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$

    LGUI: $$mdi:microsoft-windows-classic$$
    RGUI: $$mdi:microsoft-windows-classic$$
    
    TAB: $$mdi:keyboard-tab$$

    CLCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$
    CAPSLOCK: $$mdi:apple-keyboard-caps$$

    SCROLLLOCK: $$mdi:arrow-vertical-lock$$
    SLCK: $$mdi:arrow-vertical-lock$$
    SCLK: $$mdi:arrow-vertical-lock$$

    KP_NLCK: $$mdi:numeric-off$$

    PSCRN: $$mdi:monitor-screenshot$$
    PAUSE_BREAK: Pause Break
    
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    
    C_MUTE: $$mdi:volume-mute$$
    C_VOL_UP: $$mdi:volume-plus$$
    C_VOL_DN: $$mdi:volume-minus$$
    
    C_BRI_UP: $$tabler:brightness-up$$
    C_BRI_DN: $$tabler:brightness-down$$
    # C_BRI_UP: $$mdi:brightness-5$$
    # C_BRI_DN: $$mdi:brightness-4$$
    
    C_POWER: $$mdi:power$$
    C_SLEEP: $$mdi:power-sleep$$
    C_AL_CALC: $$mdi:calculator$$
    
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$
    
    PG_UP: PG UP
    PG_DN: PG DN

    # HOME: $$mdi:format-horizontal-align-left$$
    # END: $$mdi:format-horizontal-align-right$$

    SECT: '§'
    DEG: '°'
    EURO: '€'

    A_UMLAUT: 'Ä'
    AE: 'Ä'
    U_UMLAUT: 'Ü'
    UE: 'Ü'
    O_UMLAUT: 'Ö'
    OE: 'Ö'
    SZ: 'ß'
    ACUTE: '´'
    
    # default
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'